# Generated by Django 4.1.1 on 2022-09-30 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_autumn',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_spring',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='other_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
