# Generated by Django 4.1.1 on 2022-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longtitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='add_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_autumn',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_spring',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='other_titles',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pending', 'В обработке'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='fam',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
