# Generated by Django 4.1.1 on 2022-10-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_users_phone_alter_coords_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coord_id',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='perevalimages',
            old_name='img',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='perevalimages',
            old_name='pereval_id',
            new_name='pereval',
        ),
    ]
