# Generated by Django 4.1.1 on 2022-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_users_phone_alter_users_fam_alter_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
