# Generated by Django 4.1.1 on 2022-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_perevaladded_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longtitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='add_time',
            field=models.CharField(max_length=50),
        ),
    ]
