# Generated by Django 4.1.1 on 2022-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='other_titles',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
